# Generated by Django 2.2 on 2021-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_night_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='street_two',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
