# Generated by Django 2.2 on 2021-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_night_app', '0002_event_street_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_game',
            name='max_buy',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cash_game',
            name='min_buy',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='buy_in',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
